create TABLE ProgrammingQuestion(
    ID int not null AUTO_INCREMENT,
    CONTENT TEXT,
    ANSWER VARCHAR(255),
    DURATION_HOUR int,
    PAPER_ID int,
    PRIMARY KEY (ID),
    FOREIGN KEY (PAPER_ID) REFERENCES ProgrammingQuestionPaper(ID) ON DELETE CASCADE ON UPDATE CASCADE
);