create TABLE ProgrammingQuestion(
    ID CHAR(36) not null,
    CONTENT TEXT,
    ANSWER VARCHAR(255),
    DURATION_HOUR int,
    PAPER_ID CHAR(36),
    PRIMARY KEY (ID),
    FOREIGN KEY (PAPER_ID) REFERENCES ProgrammingQuestionPaper(ID) ON DELETE CASCADE ON UPDATE CASCADE
);